export enum MessageTypeEnum {
  FRONTEND_CONNECT_CONFIRMATION =0,
  API_CONNECT_REQUEST ,
  API_CONNECT_REPLY,
  GAMEFEED_CONNECT_REQUEST,
  GAMEFEED_CONNECT_REPLY,
  GET_TOP_8_REQUEST,
  GET_TOP_8_REPLY,
  GET_TOP_8_UPDATE
}
