export enum MessageTypeEnum {
  FRONTEND_CONNECT_REQUEST,
  FRONTEND_CONNECT_CONFIRM,
  API_CONNECT_REQUEST,
  API_CONNECT_REPLY,
  GAMEFEED_CONNECT_REQUEST,
  GAMEFEED_CONNECT_REPLY,
  TOP_8_SET_PREFS,
  TOP_8_GET_PREFS,
  GET_TOP_8_REQUEST,
  GET_TOP_8_REPLY,
  GET_TOP_8_UPDATE

}
